In [17]:
import pandas as pd
import yfinance as yf
import datetime
from datetime import date, timedelta
today = date.today()

d1 = today.strftime("%Y-%m-%d")
end_date = d1
d2 = date.today() - timedelta(days=365)
d2 = d2.strftime("%Y-%m-%d")
start_date = d2

data = yf.download('AMZN', 
                      start=start_date,  
                      end=end_date, 
                      progress=False)
print(data.head())

                  Open        High         Low       Close   Adj Close  \
Date
2022-06-23  110.389999  113.000000  107.930000  112.440002  112.440002
2022-06-24  112.379997  116.709999  111.430000  116.459999  116.459999
2022-06-27  117.089996  117.980003  112.699997  113.220001  113.220001
2022-06-28  113.500000  114.849998  107.040001  107.400002  107.400002
2022-06-29  107.379997  110.989998  106.910004  108.919998  108.919998

              Volume
Date
2022-06-23  64345300
2022-06-24  69867600
2022-06-27  62133200
2022-06-28  74942900
2022-06-29  66375300

In [22]:
data["Date"] = data.index
data = data[["Date", "Open", "High", 
             "Low", "Close", "Adj Close", "Volume"]]
data.reset_index(drop=True, inplace=True)
print(data.head())

        Date        Open        High         Low       Close   Adj Close  \
0 2022-06-23  110.389999  113.000000  107.930000  112.440002  112.440002
1 2022-06-24  112.379997  116.709999  111.430000  116.459999  116.459999
2 2022-06-27  117.089996  117.980003  112.699997  113.220001  113.220001
3 2022-06-28  113.500000  114.849998  107.040001  107.400002  107.400002
4 2022-06-29  107.379997  110.989998  106.910004  108.919998  108.919998

     Volume
0  64345300
1  69867600
2  62133200
3  74942900
4  66375300

In [23]:
data.keys()

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [24]:
data

,Date,Open,High,Low,Close,Adj Close,Volume
0,2022-06-23,110.389999,113.000000,107.930000,112.440002,112.440002,64345300
1,2022-06-24,112.379997,116.709999,111.430000,116.459999,116.459999,69867600
2,2022-06-27,117.089996,117.980003,112.699997,113.220001,113.220001,62133200
3,2022-06-28,113.500000,114.849998,107.040001,107.400002,107.400002,74942900
4,2022-06-29,107.379997,110.989998,106.910004,108.919998,108.919998,66375300
...,...,...,...,...,...,...,...
246,2023-06-15,125.209999,127.690002,124.320000,127.110001,127.110001,60458500
247,2023-06-16,127.709999,127.900002,125.300003,125.489998,125.489998,84188100
248,2023-06-20,124.970001,127.250000,124.500000,125.779999,125.779999,56930100
249,2023-06-21,125.639999,126.730003,123.849998,124.830002,124.830002,52137700
250,2023-06-22,125.309998,130.330002,125.139999,130.149994,130.149994,90155100

In [27]:
data1 = yf.download(['FSLR', 'NVDA', 'ARKK', 'SPY'], period='1y')
print(data1)

[*********************100%***********************]  4 of 4 completed
            Adj Close                                          Close  \
                 ARKK        FSLR        NVDA         SPY       ARKK
Date
2022-06-23  44.029999   69.599998  162.115997  371.985535  44.029999
2022-06-24  45.830002   70.070000  171.118546  383.812408  45.830002
2022-06-27  44.799999   70.620003  168.550690  382.346375  44.799999
2022-06-28  42.169998   67.750000  159.688019  374.533936  42.169998
2022-06-29  41.509998   66.839996  155.291641  374.228943  41.509998
...               ...         ...         ...         ...        ...
2023-06-16  44.310001  188.990005  426.920013  439.459991  44.310001
2023-06-20  44.259998  186.100006  438.079987  437.179993  44.259998
2023-06-21  42.660000  184.580002  430.450012  434.940002  42.660000
2023-06-22  42.669998  187.080002  430.250000  436.510010  42.669998
2023-06-23  41.680000  186.089996  422.548004  433.760010  41.680000

                                                     High              ...  \
                  FSLR        NVDA         SPY       ARKK        FSLR  ...
Date                                                                   ...
2022-06-23   69.599998  162.250000  378.059998  44.240002   69.870003  ...
2022-06-24   70.070000  171.259995  390.079987  45.990002   70.599998  ...
2022-06-27   70.620003  168.690002  388.589996  46.270000   71.529999  ...
2022-06-28   67.750000  159.820007  380.649994  45.369999   70.959999  ...
2022-06-29   66.839996  155.419998  380.339996  42.240002   67.489998  ...
...                ...         ...         ...        ...         ...  ...
2023-06-16  188.990005  426.920013  439.459991  45.000000  195.179993  ...
2023-06-20  186.100006  438.079987  437.179993  44.709999  190.300003  ...
2023-06-21  184.580002  430.450012  434.940002  44.330002  187.169998  ...
2023-06-22  187.080002  430.250000  436.510010  42.799999  188.470001  ...
2023-06-23  186.089996  422.548004  433.760010  42.180000  188.710007  ...

                   Low                   Open                          \
                  NVDA         SPY       ARKK        FSLR        NVDA
Date
2022-06-23  158.529999  372.890015  41.630001   68.550003  165.190002
2022-06-24  163.100006  381.369995  44.770000   70.250000  165.000000
2022-06-27  166.259995  387.440002  45.825001   70.379997  173.119995
2022-06-28  159.449997  380.529999  44.730000   70.879997  169.000000
2022-06-29  151.699997  378.420013  41.889999   66.779999  158.139999
...                ...         ...        ...         ...         ...
2023-06-16  426.609985  438.970001  44.950001  193.940002  434.500000
2023-06-20  426.739990  435.029999  44.009998  189.289993  429.980011
2023-06-21  420.799988  434.329987  44.299999  186.100006  435.010010
2023-06-22  422.339996  433.600006  42.290001  183.660004  422.529999
2023-06-23  420.179993  432.711700  41.930000  183.369995  424.640015

                          Volume
                   SPY      ARKK     FSLR      NVDA        SPY
Date
2022-06-23  376.640015  33227400  1354600  46368000   79292100
2022-06-24  381.399994  35391300  1271800  47215300   98050300
2022-06-27  391.049988  27260900   916700  42796800   66009600
2022-06-28  390.230011  32045400  1431700  46114900   86548900
2022-06-29  381.230011  19880400  1231900  48235200   65676000
...                ...       ...      ...       ...        ...
2023-06-16  443.019989  12963100  3106000  65475500  114121300
2023-06-20  437.450012  10835300  2077800  45115300   76160400
2023-06-21  436.160004  16387400  1680200  55160300   76982300
2023-06-22  433.950012  10907500  1443700  41692600   70436800
2023-06-23  432.929993   4143152   368506  10037771   14912607

[252 rows x 24 columns]

In [30]:
data1 = yf.download(['AAPL', 'FSLR', 'NVDA', 'ARKK', 'SPY'], period='1y')['Close']
correlation_matrix = data1.corr()
print(correlation_matrix)

[*********************100%***********************]  5 of 5 completed
          AAPL      ARKK      FSLR      NVDA       SPY
AAPL  1.000000  0.512193  0.346084  0.773069  0.804413
ARKK  0.512193  1.000000 -0.421354  0.136112  0.446358
FSLR  0.346084 -0.421354  1.000000  0.647987  0.419485
NVDA  0.773069  0.136112  0.647987  1.000000  0.768262
SPY   0.804413  0.446358  0.419485  0.768262  1.000000